# installing redis service using ansible
# redis is an in-memory data structure store, used as a database, cache, and message broker

-  name: redis service
   hosts: redis
   become: yes
   tasks:
   -  name: install remi release rpm
      ansible.builtin.dnf:
        name: https://rpms.remirepo.net/enterprise/remi-release-8.7.rpm 
        state: present
        disable_gpg_check: yes # Disables GPG check for the package installation

   -  name: enable redis module
      ansible.builtin.shell: dnf module enable redis:remi-6.2 -y

   -  name: install redis
      ansible.builtin.dnf:
        name: redis
        state: present
       
   -  name: allow remote connections
      ansible.builtin.replace:
        path: /etc/redis/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

   -  name: start and enable redis
      ansible.builtin.service:
        name: redis
        state: started
        enabled: yes                